moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - arm_1/joint_trajectory_controller
    - arm_2/joint_trajectory_controller

  arm_1/joint_trajectory_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - arm_1_shoulder_pan_joint
      - arm_1_shoulder_lift_joint
      - arm_1_elbow_joint
      - arm_1_wrist_1_joint
      - arm_1_wrist_2_joint
      - arm_1_wrist_3_joint

  arm_2/joint_trajectory_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - arm_2_shoulder_pan_joint
      - arm_2_shoulder_lift_joint
      - arm_2_elbow_joint
      - arm_2_wrist_1_joint
      - arm_2_wrist_2_joint
      - arm_2_wrist_3_joint